name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server via SSH and run commands
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          if [ -d "${{ secrets.BASE_DIR }}" ]; then
              cd ${{ secrets.BASE_DIR }}
              git pull
              echo "git pull done"
          else
              echo "Directory ${{ secrets.BASE_DIR }} does not exist."
              exit 1
          fi
          EOF
      - name: Start project
        run: |
          chmod +x setup_ubuntu_mac.sh
          ./setup_ubuntu_mac.sh